services:
  - type: web
    name: liver-disease-backend
    env: python
    plan: free
    rootDir: backend
    buildCommand: pip install -r requirements.txt
    startCommand: python app.py
    pythonVersion: 3.10.13
